# Generated by Django 4.2.11 on 2024-05-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='research/', verbose_name='research_image'),
        ),
    ]
