# Generated by Django 4.2.11 on 2024-05-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_research_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='teaching/', verbose_name='teaching_image')),
            ],
            options={
                'verbose_name': 'Teaching',
                'verbose_name_plural': 'Teaching',
            },
        ),
    ]
