# Generated by Django 4.2.11 on 2024-05-03 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0002_navbar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navbar',
            old_name='name',
            new_name='page',
        ),
    ]
